ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
DIP_SWITCH_ENABLE = yes
SEND_STRING_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c
OLED_ROTATION_180 = yes

BOOTMAGIC_ENABLE = yes